language: android

jdk:
- oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - android-28
  - build-tools-28.0.3
sudo: false

script: gradle/buildViaTravis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

env:
  global:
    - secure: jp91pn7F7GVrN2AQ5RTGrDIWejSmjWPM1gAjTSpH3fTynVHfzAl273KUKJBWNOG6/B5AH5N0lOoH8b3cUu90ygZwG/6lSlEck+0uCkQTELqGUT+fL5o8couacBrhXvWwedEebf3ABFQsxhlwzE/7SerbpT3ltFtl4CupejvPiNyaGdy/oMIHWcfuiZpZxy8uu2eSgiiapH45F4SC9+z7zxQGtWMw0MFFzbYW7kHPPxAOpbDPNoYHzYAYHb6jvjKfn1kwqHNrBDgsGSyCrtdvJAw/ZNVt54O79gHuatYCHXpIGAZReMdhV2t4Tk2ZhkV1ItQPbi7jbXjDwhHmjIMjP1w0o/OifCc1xYMIXg6WWyUQSSYqDVndUqn7RO8XdvRdYDAm+RvaRpfWp+LCcmsDaahSB1v9jvLOVY1PggFQkric9mh9OlbZk77cnFgEg8Z5u/LDVlfFqoWQ9/yCOlV5Ycp4ChDaQbqqVNIyxgJkxAJioboxy3f+yzsW7j9Tw/RHwqmKNJngjfTv3W2JkqiSwyvgpxQ/zdLYXt7TJ+kU+vBWzpsuqhmIWxvQlsNQBMkOmZFia7ey05alnuZ1yIfxSC+yZwDBXN9nU6XyM5zg5b/b34UG/6kyYhuOyQKqIHPC+IvGH8rvnqR3AM4qxnndz+ZdNR0Ev+VY7QM8EKX+sO8=
    - secure: PkuwFTXHKVebNfqiC7T/LLdhRamz6+V0CjwW+GLlKvGH926FmbzwHajup/RFhAnsMXvajI/yKbx3wIOJI1bPsWYmCnhVkw+Zscko2XcOZcXFxEB9Dl36XxvK5RLBLVXxJraRFnyGf860r+8ys+xZJKVUyi5WVYzpiBCXMgQ6AekTNMClU2DgfVjME545WMkMFYF+qVJkGYdVRZeph6bn+vK0CLgRbIxk5x1Z0ACEM4AeLW0Z8zapfRV2IOqkuAZEIWWd/jGJaB0hwi83BtE4Ety2XUm3mhd1MZL5xMmMPWgRDPoVP6yrQbkL06XF67QuybKV9cspojXo+tL507Q/3iFblPQKSNx/CFJr7hzjvCFlWw22Xm4RueymPcZDB7/ohlJxrh3gEJk+cDKKQypesqGphal50Srnpi7axM/SKl21gYMqBebhUb/4kAoPy1E+zQMRFmLyztwXJovr4ROug0VWa2ovPfccHNGP4x+O1/uDIlIBE4mQX0l0RNhIPAV6HOnwmarko8AvItF/aPE3PFVMjH47ugLVhUPlP0D2GPbR1jKnqdsk97eA5BAlfgK2JFy9WLMwUuS1cTR8L+e9lqgdzMNXSRQ7iATct2nr7xaFWcJltIVAiR8IFfVtLrhlDam//5lIZhDu5rseaNnqbEPCs/MR5xZMQlquzGfz00w=
